### ISSUE TITLE
Use built-in collections methods to decrease the amount of database calls

### ISSUE THREAD

**Issue by Lippur** [JasperSijgers/abs#1]
In Models/Groups/MailingList.php

`
public function hasSubscriber(User $user)
    {
        foreach($this->subscribers as $subscriber){
            if($subscriber->user && $subscriber->user == $user){
                return true;
            }
        }
        return false;
    }
`

could be replaced with

`
$this->subscribers->contains($user);
`

This reduces the amount of database queries to 1.

**Comment by JasperSijgers** [comment]
Solved in 31334456763037ba1ec52f628e672a8d54462e48
