### ISSUE TITLE
"Validate" button for SEPA needs several klicks for error notification (Bug)

### ISSUE THREAD

**Issue by ErnstJanPeters** [JasperSijgers/abs#4]
The "validate" button for a SEPA validation needs several klicks to give the error notification

**Comment by JasperSijgers** [comment]
I can't seem to replicate the issue. Please note that validating a CSV file takes time, depending on the size of the file (the amount of lines to be validated). The validation process is done in the background, and will therefore not refresh the page once finished. Try refreshing the page after a few seconds, and seeing if it's been validated.

Clicking the validation button multiple times won't speed up the process, it'll only attempt to validate the same file multiple times.

**Comment by JasperSijgers** [comment]
Multiple clicks now no longer start multiple validation attempts, but instead warn the user validation is already in progress.

Once validation finishes, the user gets a popup displaying its result, and the page gets refreshed automatically after the popup disappears.
